### ISSUE TITLE
Buildpack compilation step failed

### ISSUE THREAD

**Issue by djannot** [cloudfoundry/dea_ng#170] opened 2015-07-22 16:57 UTC
I try to push a golfing application, but I get the following errors:

Starting app s3pics in org s3pics / space development as admin...
-----> Downloaded app package (163M)
Cloning into '/tmp/buildpacks/go-buildpack'...
Submodule 'compile-extensions' (https://github.com/cloudfoundry-incubator/compile-extensions.git) registered for path 'compile-extensions'
Cloning into 'compile-extensions'...
Submodule path 'compile-extensions': checked out 'f752ecf4b27d2f31bb082dfe7a47c76fefc769d7'
-------> Buildpack version 1.4.0
-----> Resource https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz does not exist.
-----> Installing go1.4.2...Staging failed: Buildpack compilation step failed

I've tried with CF_TRACE=true, but don't get more useful information.

It looks it can't download the go1.4.2 archive and it could be due to our firewall.
I generally need to install our certificates on clients, so I've tried to install them on several CF VMs, like the controller, the DAE, ... But, I still have the same issue.

Any idea ? Could I install it manually ?

**Comment by Amit-PivotalLabs** [comment] 2015-07-23 18:22
Hi @djannot,

Here's the line in the go-buildpack's `compile` script that's likely failing:

https://github.com/cloudfoundry/go-buildpack/blob/v1.4.0/bin/compile#L111

Unfortunately the log information is a bit opaque, and it's not entirely clear exactly what URL it's trying to download, whether the `curl` failed and if so why, or whether the `tar` failed and if so why.  One thing we could try, if you're able to get a different app running, is to get into another app container and manually try what the buildpack is trying, to see what the cause of the error is.  We can try to figure out if it's networking or something else.

/cc @flavorjones @mhoran (go-buildpack-1.4.0 is failing to fetch golang 1.4.2, not clear why from the error message)

**Comment by mhoran** [comment] 2015-07-23 19:18
I was able to grab the go tarball linked in the issue without issue. My guess is that the compile is failing due to the firewall, as @djannot suspected. It looks like the `-b` parameter was provided to `cf push`, which will use an online buildpack. We'd recommend trying to use one of the built-in buildpacks, or uploading an admin buildpack via the command line. In that case, the buildpack distributed at https://github.com/cloudfoundry/go-buildpack/releases can be used, which is built for offline.

**Comment by Amit-PivotalLabs** [comment] 2015-07-23 21:16
@mhoran I noticed the log line says:

```
-----> Resource https://storage.googleapis.com/golang/go1.4.2.linux-amd64.tar.gz does not exist.
```

That URL is the `$url` variable in the compile script.  However, the actual curl command is this:

```
(curl `translate_dependency_url $ver` -s --fail -o - | tar xzf - -C $cache/$ver 2>/dev/null)
```

So we don't know whether `translate_dependency_url $ver` is the same as `$url`.

That said, @djannot can you try @mhoran's suggestion of using the offline buildpack, which will include a version of go bundled in, and won't need to fetch it from storage.googleapis.com.

**Comment by djannot** [comment] 2015-07-23 21:50
@Amit-PivotalLabs @mhoran Thanks for your help.

I found a workaround.

When I push my app using cf push -b compile-extensions -b go_buildpack s3pics, it's using the local buildpacks, so it works. But it would be nice to allow adding trusted SSL certificates to avoid this kind of issues.

**Comment by Amit-PivotalLabs** [comment] 2015-07-23 22:43
Hi @djannot,

Glad you got your push to work!

It's not clear that the SSL cert is the issue.  It may be, but I don't see conclusive evidence of that, it looks like a number of things could have gone wrong in that `curl ... | tar ...` command.  Again, if you SSH'd onto the DEA and then start a warden shell session into a currently-working app container (we can give you more details on how to do this) then you can manually run some of the curl and tar commands and see exactly why it's failing.

The root file-system (aka stack or rootfs) for the containers and the base image for the DEA VM (aka stemcell) are designed to be essentially the same for any installation of Cloud Foundry, so if other installations are able to trust the cert, then yours should be to.  It's possible that the problem is upstream, outside of Cloud Foundry, if traffic is going through a network gateway/firewall.

I'll close this issue out for now, if you have further issues feel free to open a new one.

Thanks,
Amit

**Closed by Amit-PivotalLabs** 2015-07-23 22:43 UTC

**Comment by mhoran** [comment] 2015-07-24 13:28
@Amit-PivotalLabs: While the go-buildpack does utilize `translate_dependency_url`, our manifest specifies storage.google.com as the location for the buildpack. You'll notice the source and translated URL are identical in the [manifest](https://github.com/cloudfoundry/go-buildpack/blob/master/manifest.yml).

Most other buildpacks reference the pivotal-buildpacks S3 bucket, but we left the go-buildpack at its original source location. `translate_dependency_url` is used in this case to allow offline use -- but that is not enabled when the `-b` option is provided.
